Try add duration to service
Seven-dev7/beautyCure pull request #4
Opened 2020-09-18 08:33 UTC by Seven-dev7

add all services value by seed
add duration to services

2020-09-23 13:04 UTC, jpmagido commented on app/views/products/show.html.erb
> +<%= @product.description %>
endline

2020-09-23 13:05 UTC, jpmagido commented on config/routes.rb
> +  resources :cart_services, only: [:show, :index, :create, :new]
Pourquoi ?

2020-09-23 13:06 UTC, jpmagido commented on db/migrate/20200914142427_create_cart_services.rb
> +      t.integer :quantity, default: 1
pourquoi ?

2020-09-23 13:07 UTC, jpmagido commented on app/views/services/index.html.erb
> +
Il va falloir refacto tout ça, c'est très moche ^^

2020-09-23 13:11 UTC, jpmagido commented on app/views/orders/index.html.erb
> +<p>Find me in app/views/orders/index.html.erb</p>
Comment vas-tu te servir de cet Index ?

2020-09-23 13:12 UTC, jpmagido commented on app/views/cart_services/show.html.erb
> +<p>Find me in app/views/cart_services/show.html.erb</p>
Pourquoi y a t-il une view pour une table de jointure ?

2020-09-23 13:12 UTC, jpmagido commented on app/views/cart_services/index.html.erb
> +<p>Find me in app/views/cart_services/index.html.erb</p>
Pourquoi y a t-il une view pour une table de jointure ?

2020-09-23 13:12 UTC, jpmagido commented on app/views/cart/show.html.erb
> +<p><%= link_to "Retour aux produits", services_path %></p>
Endline

2020-09-23 13:13 UTC, jpmagido commented on app/controllers/cart_services_controller.rb
> +end
HEIN ?!

2020-09-23 13:14 UTC, jpmagido commented on app/controllers/concerns/current_cart.rb
> +end
Je ne pense pas que ça soit necessaire.

2020-09-23 13:15 UTC, jpmagido commented on db/seeds.rb
> +p 'seed done !  dedicasse a JPette'
endline

2020-09-23 13:19 UTC, jpmagido requested changes
Il faut revoir le fonctionnement du panier

2020-09-24 11:32 UTC, jpmagido commented on app/controllers/carts_controller.rb
> +    redirect_to cart_path(current_user.cart.id)
Tu peux utiliser le `params[:cart_id]` au lieu du `current_user.car.id`

2020-09-24 11:33 UTC, Seven-dev7 commented
Add devise, cancancan, test model association all, create all model, create (order, cart, service and product controller), create cart system + cart show view

2020-09-24 11:34 UTC, merged

2020-09-24 11:35 UTC, jpmagido commented on app/views/services/show.html.erb
> +    <%= button_to 'Ajouter au Panier', cart_add_service_path(cart_id: current_user.cart.id, service_id: @service.id), class: "btn btn-primary"%>
Attention, la page va casser quand tu y accèdes hors connexion à cause du `current_user`
Il faut par exemple ajouter un if